from .poly import to_poly2, to_polyn, to_poly3
from .latex import to_latex
from .linear import to_linear
from .log_exp import to_log, to_exp

__version__ = "0.1.7"
__author__ = "Téo JAUFFRET"
__description__ = "A small python lib to convert coef generated by scipy and other scientifc libraries into readble functions (latex support)"

__log_update__ = [
    '0.1 : Initial release',
    '0.1.2 : Added support for latex output'
    '0.1.3 : Added support for linear functions',
    '0.1.4 : Added support for log and exp functions',
    '0.1.5 : Fix bug in to_log func (\\ln instead of ln)',
    '0.1.6 : Fix bug in to_latex func (added missing {} in exponents)',
    '0.1.7 : Fix bug for negative coefficients in to_latex func (added () around negative numbers) and fix bug for coef = 0'
]